spring:
  cloud:
    gateway:
      server:
        webflux:
#          routes:
#            - id: bing-route
#              uri: https://cn.bing.com
#              predicates:
#                - Path=/**
#              order: 10
              # id 全局唯一

#            - id: order-route
#              # 指定服务名称
#              uri: lb://service-order
#              # 指定断言规则，即路由匹配规则
#              predicates:
#                - Path=/api/order/**
#              order: 1
#            - id: product-route
#              uri: lb://service-product
#              predicates:
#                - Path=/api/product/**
#              order: 2


#            - id: order
#              uri: lb://service-consumer
#              predicates:
#                - Path=/order/**
#            - id: Vip
#              uri: https://cn.bing.com
#              predicates:
#                - Path=/search
#                - Query=q,hi
#                - Vip=user,Shannon

          #⭐default-filters:不生效 因为webflux版本原因
#          default-filters:
#            - AddRequestHeader=X-Request-Foo, Bar

          #跨域配置
          globalcors:
            cors-configurations:
              '[/**]':
                #请求来源地址
                allowed-origin-patterns: '*'
                allowed-headers: '*'
                allowedMethods: '*'